-- Truth or Dare: Round 1 new truths (46 clean + 25 spicy), picked via checkbox shortlist artifact
insert into truth_dare_prompts (type, text, dirty, like_count, dislike_count) values
('truth', 'What''s a habit you have that you''d never admit to a stranger?', false, 0, 0),
('truth', 'What''s the most embarrassing thing that''s happened to you at school or work?', false, 0, 0),
('truth', 'Who''s the last person you stalked on social media?', false, 0, 0),
('truth', 'What''s a secret talent nobody in this room knows about?', false, 0, 0),
('truth', 'What''s the dumbest thing you''ve ever cried about?', false, 0, 0),
('truth', 'What''s the most trouble you''ve ever gotten into?', false, 0, 0),
('truth', 'What''s a text you sent to the wrong person?', false, 0, 0),
('truth', 'What''s the weirdest dream you''ve had about someone in this room?', false, 0, 0),
('truth', 'What''s a food combo you love that everyone judges you for?', false, 0, 0),
('truth', 'What''s the most awkward thing you''ve said on a first date?', false, 0, 0),
('truth', 'Who do you think is most likely to become famous in this room?', false, 0, 0),
('truth', 'What''s a childhood nickname you''re embarrassed by?', false, 0, 0),
('truth', 'What''s the last thing you lied to your parents about?', false, 0, 0),
('truth', 'What''s the pettiest thing you''ve ever done for revenge?', false, 0, 0),
('truth', 'What''s a rule you always break?', false, 0, 0),
('truth', 'What''s the most useless talent you have?', false, 0, 0),
('truth', 'What''s a purchase you regret the most?', false, 0, 0),
('truth', 'What''s the most embarrassing song on your playlist?', false, 0, 0),
('truth', 'What''s the weirdest thing you''ve done to impress someone?', false, 0, 0),
('truth', 'What''s a secret you kept from your best friend?', false, 0, 0),
('truth', 'What''s the most childish thing you still do?', false, 0, 0),
('truth', 'What''s a white lie you tell often?', false, 0, 0),
('truth', 'What''s the most embarrassing thing your parents have caught you doing?', false, 0, 0),
('truth', 'Who''s the messiest person in this room?', false, 0, 0),
('truth', 'What''s the most cringeworthy thing you''ve posted online?', false, 0, 0),
('truth', 'What''s your biggest ick?', false, 0, 0),
('truth', 'What''s a job you''d be terrible at?', false, 0, 0),
('truth', 'What''s your most controversial food opinion?', false, 0, 0),
('truth', 'What''s something you pretend to understand but don''t?', false, 0, 0),
('truth', 'What''s the most embarrassing thing you''ve done in front of a crush?', false, 0, 0),
('truth', 'Who in this room do you think has the most secrets?', false, 0, 0),
('truth', 'What''s a promise you never kept?', false, 0, 0),
('truth', 'What''s the worst advice you''ve ever given?', false, 0, 0),
('truth', 'What''s the most awkward silence you''ve ever caused?', false, 0, 0),
('truth', 'What''s your go-to excuse to leave somewhere early?', false, 0, 0),
('truth', 'What''s the most embarrassing outfit you''ve ever worn in public?', false, 0, 0),
('truth', 'What''s a grudge you''re still holding onto?', false, 0, 0),
('truth', 'What''s the last thing you apologized for but didn''t mean it?', false, 0, 0),
('truth', 'What''s the weirdest compliment you''ve ever received?', false, 0, 0),
('truth', 'What''s the most embarrassing thing that''s happened to you on a night out?', false, 0, 0),
('truth', 'What''s a household chore you always avoid?', false, 0, 0),
('truth', 'What''s the worst excuse you''ve ever used to get out of plans?', false, 0, 0),
('truth', 'What''s the most embarrassing thing you''ve done for attention?', false, 0, 0),
('truth', 'What''s a conspiracy theory you secretly believe?', false, 0, 0),
('truth', 'Who in this room texts you the most, and what''s it usually about?', false, 0, 0),
('truth', 'What''s a talent show act you''d actually perform right now if you had to?', false, 0, 0),
('truth', 'What''s the most attractive quality you look for in someone?', true, 0, 0),
('truth', 'Have you ever had a crush on someone else''s partner?', true, 0, 0),
('truth', 'What''s the boldest move you''ve ever made on someone?', true, 0, 0),
('truth', 'Who in this room would you swipe right on?', true, 0, 0),
('truth', 'What''s the most scandalous thing you''ve done at a party?', true, 0, 0),
('truth', 'Have you ever hooked up with someone you regret?', true, 0, 0),
('truth', 'What''s your biggest turn-off?', true, 0, 0),
('truth', 'What''s the wildest place you''ve hooked up?', true, 0, 0),
('truth', 'Who''s the best kisser you''ve ever kissed?', true, 0, 0),
('truth', 'What''s a fantasy you''ve never told anyone?', true, 0, 0),
('truth', 'Have you ever sent a risky text to the wrong person?', true, 0, 0),
('truth', 'What''s the most attractive thing someone can wear?', true, 0, 0),
('truth', 'What''s the longest you''ve gone without a relationship, and why?', true, 0, 0),
('truth', 'Have you ever cheated or been tempted to?', true, 0, 0),
('truth', 'What''s your biggest turn-on?', true, 0, 0),
('truth', 'What''s the most embarrassing thing that''s happened to you in bed?', true, 0, 0),
('truth', 'Who''s someone in this room you''d date if you were single?', true, 0, 0),
('truth', 'Have you ever had a crush on a friend''s ex?', true, 0, 0),
('truth', 'What''s the most inappropriate place you''ve thought about hooking up?', true, 0, 0),
('truth', 'Have you ever faked being into someone just to see where it went?', true, 0, 0),
('truth', 'What''s the cheesiest pickup line that''s actually worked on you?', true, 0, 0),
('truth', 'Who was your most awkward "it''s complicated" situation?', true, 0, 0),
('truth', 'What''s the drunkest you''ve ever been around your crush?', true, 0, 0),
('truth', 'Have you ever been caught checking someone out?', true, 0, 0),
('truth', 'What''s a red flag you ignored because someone was hot?', true, 0, 0);
