-- Append batches 8 and 9 of curated Never Have I Ever statements.
insert into nhie_statements (statement, dirty, like_count, dislike_count) values
('lied about my "number" to seem less experienced', true, 0, 0),
('pretended an ex didn''t exist when talking to someone new', true, 0, 0),
('kept a "situationship" going way longer than I should have', true, 0, 0),
('had a friend''s ex hit on me', true, 0, 0),
('gotten caught by a roommate mid-hookup', true, 0, 0),
('had a hookup buddy for over a year', true, 0, 0),
('slid back into an ex''s DMs after months of no contact', true, 0, 0),
('had a one-night stand turn into something longer', true, 0, 0),
('lied about liking something in bed to avoid an awkward talk', true, 0, 0),
('lied when asked "how many people" I''ve been with', true, 0, 0),
('hooked up with someone purely out of boredom', true, 0, 0),
('used alcohol as an excuse for a hookup I actually wanted', true, 0, 0),
('said "we''re just having fun" when it clearly wasn''t just fun for me', true, 0, 0),
('texted an ex while in a new relationship', true, 0, 0),
('gotten caught in a lie about a past relationship', true, 0, 0),
('had an ex''s friend message me', true, 0, 0),
('pretended to be more experienced than I actually am', true, 0, 0),
('had someone find messages on my phone I didn''t want them to see', true, 0, 0),
('sent something risky to the wrong group chat', true, 0, 0),
('had a hookup I only remember parts of', true, 0, 0),
('had to ask for someone''s name again the next morning', true, 0, 0),
('been accused of cheating when I actually was', true, 0, 0),
('lied about being ready for a relationship just to keep someone around', true, 0, 0),
('lied on my resume or CV', false, 0, 0),
('googled my symptoms and convinced myself I was dying', false, 0, 0),
('pretended to be happy for someone when I really wasn''t', false, 0, 0),
('avoided answering a call because I didn''t want to deal with it', false, 0, 0),
('lied to a friend about why I couldn''t make it to something', false, 0, 0),
('pretended not to care about something that really hurt', false, 0, 0),
('lied to get out of paying for something', false, 0, 0),
('taken credit for someone else''s idea', false, 0, 0),
('avoided a friend for weeks without telling them why', false, 0, 0),
('pretended to laugh at a joke I didn''t actually understand', false, 0, 0),
('said something petty just to win an argument', false, 0, 0),
('lied about being busy to skip a family event', false, 0, 0),
('judged someone based on their appearance and regretted it', false, 0, 0),
('talked myself out of an opportunity out of fear', false, 0, 0),
('pretended not to notice someone was upset with me', false, 0, 0),
('gone into debt for something I didn''t need', false, 0, 0),
('hidden a purchase from a partner or family member', false, 0, 0),
('lied about how much something cost', false, 0, 0),
('let someone take the blame for something I did', false, 0, 0),
('avoided a family member on purpose for months', false, 0, 0),
('lied about how I really feel just to keep the peace', false, 0, 0);
