-- Append batches 3, 4 and 5 of curated Never Have I Ever statements.
insert into nhie_statements (statement, dirty, like_count, dislike_count) values
('showed up an hour early to something by mistake', false, 0, 0),
('forgotten to hit send on a message and found it days later', false, 0, 0),
('pretended to like a gift I actually hated', false, 0, 0),
('gotten scared by my own reflection', false, 0, 0),
('accidentally worn my shirt inside out all day', false, 0, 0),
('gotten a haircut right before a big event and regretted it', false, 0, 0),
('laughed at my own joke before finishing it', false, 0, 0),
('pretended to be on the phone to avoid a stranger', false, 0, 0),
('sent an email to the wrong recipient at work', false, 0, 0),
('gotten a song''s lyrics wrong for years without realizing it', false, 0, 0),
('said "love you" to someone I wasn''t supposed to, out of habit', false, 0, 0),
('accidentally posted something meant to stay a draft', false, 0, 0),
('had a crush that lasted way longer than it should have', true, 0, 0),
('hooked up with someone right after a breakup', true, 0, 0),
('had feelings for two people at the same time', true, 0, 0),
('stayed up all night texting someone new', true, 0, 0),
('had a workplace crush I never acted on', true, 0, 0),
('gone on a date I regretted within five minutes', true, 0, 0),
('had a friendship almost turn into something more', true, 0, 0),
('lied about how many people I''ve dated', true, 0, 0),
('had someone find out I liked them before I told them', true, 0, 0),
('felt jealous seeing an ex with someone new', true, 0, 0),
('had a crush confess to me and panicked', true, 0, 0),
('flirted back and forth for weeks without making a move', true, 0, 0),
('thought "this could be the one" way too early', true, 0, 0),
('cheated on a partner and never got caught', true, 0, 0),
('been cheated on and stayed anyway', true, 0, 0),
('wanted a threesome', true, 0, 0),
('slept with someone just to make an ex jealous', true, 0, 0),
('kept someone as a "backup option" while dating someone else', true, 0, 0),
('read a partner''s private messages without permission', true, 0, 0),
('ghosted someone right after sleeping with them', true, 0, 0),
('hooked up with someone way older or younger than me', true, 0, 0),
('had an unrequited crush on a close friend''s partner', true, 0, 0),
('cheated in a relationship and genuinely never got caught', true, 0, 0),
('kept messaging an ex behind my partner''s back', true, 0, 0),
('fantasized about someone else while with my partner', true, 0, 0),
('said "I love you" and didn''t fully mean it', true, 0, 0),
('had a pregnancy scare', true, 0, 0),
('been the "other person" in someone else''s relationship', true, 0, 0),
('deleted messages so a partner wouldn''t see them', true, 0, 0),
('used someone for their money or status', true, 0, 0),
('gotten drunk and revealed a secret I really shouldn''t have', true, 0, 0),
('lied to my family about who I was dating', true, 0, 0),
('kept an entire relationship secret from my parents', true, 0, 0),
('hooked up with someone I met on a work or school trip', true, 0, 0),
('stayed friends with someone specifically hoping for more', true, 0, 0),
('lied about being exclusive with someone', true, 0, 0),
('had someone else''s name almost slip out at the wrong moment', true, 0, 0),
('hooked up with two people who know each other', true, 0, 0),
('been in love with someone who was already taken', true, 0, 0),
('told a friend''s secret to someone else', true, 0, 0),
('dated someone just to get back at an ex', true, 0, 0),
('lied about my income to impress someone', true, 0, 0),
('borrowed money and never paid it back', true, 0, 0),
('talked badly about a friend to someone they were dating', true, 0, 0),
('hooked up with someone my friend had feelings for', true, 0, 0),
('pretended not to remember a hookup out of pure embarrassment', true, 0, 0),
('sabotaged someone else''s relationship on purpose', true, 0, 0),
('lied to a partner about my past', true, 0, 0),
('used a fake name on a date', true, 0, 0),
('stayed in a relationship only because I was scared to be alone', true, 0, 0),
('told someone I loved them just to keep them around', true, 0, 0),
('cried to get out of trouble', true, 0, 0),
('lied about where money went in a relationship', true, 0, 0),
('snooped through a partner''s phone and found something I regret seeing', true, 0, 0),
('had a crush on someone I knew was already taken', true, 0, 0),
('found out I was someone''s "backup" and stayed anyway', true, 0, 0),
('lied about liking someone''s family just to keep the peace', true, 0, 0),
('pretended to have moved on from an ex when I really hadn''t', true, 0, 0),
('compared a current partner to an ex out loud', true, 0, 0),
('told a small lie that turned into a much bigger one', true, 0, 0),
('hooked up with someone and pretended I didn''t remember their name', true, 0, 0),
('broken up with someone over text', true, 0, 0),
('been jealous of a friend''s relationship', true, 0, 0),
('wished something bad on an ex''s new partner', true, 0, 0),
('stayed friends with someone I secretly couldn''t stand', true, 0, 0);
