-- Append batch 10 (curated from camillestyles.com) of Never Have I Ever statements.
insert into nhie_statements (statement, dirty, like_count, dislike_count) values
('lied about myself on a dating app', false, 0, 0),
('taken a solo trip', false, 0, 0),
('changed someone''s mind about something important', false, 0, 0),
('sent an anonymous gift', false, 0, 0),
('spied on my neighbors', false, 0, 0),
('stolen something small from a restaurant', false, 0, 0),
('made up a story about myself to impress someone', false, 0, 0),
('had a wardrobe malfunction in public', false, 0, 0),
('snuck into a movie or concert without paying', false, 0, 0),
('lied about my job to sound cooler', false, 0, 0),
('sent a text to the wrong person on purpose', false, 0, 0),
('kissed a stranger', false, 0, 0),
('ghosted someone I was dating', false, 0, 0),
('fallen in love at first sight', false, 0, 0),
('flirted with a bartender or barista', false, 0, 0),
('climbed a mountain', false, 0, 0),
('ridden a camel', false, 0, 0),
('been in a cave', false, 0, 0),
('been to a major festival like Coachella', false, 0, 0),
('lost a personal item in another country', false, 0, 0),
('been to a major sports final', false, 0, 0),
('laughed so hard I spit out my drink', false, 0, 0),
('tried to impress someone and failed miserably', false, 0, 0),
('had a funny misunderstanding', false, 0, 0),
('tried to sound smart and made a fool of myself', false, 0, 0),
('accidentally waved at a stranger thinking I knew them', false, 0, 0),
('learned a language to better communicate with someone', false, 0, 0),
('dined and dashed', false, 0, 0),
('lied to someone playing this game right now', false, 0, 0),
('drunk texted an ex', false, 0, 0),
('started a rumor', false, 0, 0),
('convinced a friend to dump their partner', false, 0, 0),
('fought with someone in public', false, 0, 0),
('gotten into a car crash', false, 0, 0),
('tried psychedelics', true, 0, 0),
('had a video go viral', false, 0, 0),
('regifted something', false, 0, 0),
('met a celebrity', false, 0, 0),
('done a prank call', false, 0, 0),
('participated in a protest', false, 0, 0),
('peed my pants as an adult', false, 0, 0),
('been to a strip club', true, 0, 0),
('been on a blind date', false, 0, 0),
('had a paranormal experience', false, 0, 0),
('been to a fortune teller', false, 0, 0),
('been hypnotized', false, 0, 0),
('collected stamps, coins, or trading cards', false, 0, 0);
