-- Replace Never Have I Ever content with the curated v2 list.
truncate table nhie_statements restart identity;

insert into nhie_statements (statement, dirty, like_count, dislike_count) values
('cheated on a test', false, 0, 0),
('pretended to know a song I''d never heard', false, 0, 0),
('fallen off a chair in public', false, 0, 0),
('texted my ex "accidentally on purpose"', false, 0, 0),
('gone through someone''s phone without asking', false, 0, 0),
('told a lie that spiraled out of control', false, 0, 0),
('shown up to the wrong event', false, 0, 0),
('peed in a pool', false, 0, 0),
('snooped through someone''s search history', false, 0, 0),
('gotten stuck in an elevator', false, 0, 0),
('lied about liking a gift', false, 0, 0),
('accidentally liked an old photo while stalking someone''s profile', false, 0, 0),
('cheated at a board game', false, 0, 0),
('sent a voice message and immediately regretted it', false, 0, 0),
('pretended to be someone else on a phone call', false, 0, 0),
('broken something valuable and blamed someone else', false, 0, 0),
('stayed friends with an ex', false, 0, 0),
('lied about my location to get out of plans', false, 0, 0),
('pretended to be busy just to avoid someone', false, 0, 0),
('gotten a bad haircut and pretended to love it', false, 0, 0),
('driven somewhere and forgotten why', false, 0, 0),
('faked an accent', false, 0, 0),
('snuck into a place I wasn''t supposed to be', false, 0, 0),
('accidentally sent a text to the person it was about', false, 0, 0),
('had a crush on a teacher or coach', true, 0, 0),
('almost sent a nude to the wrong person', true, 0, 0),
('regretted a hookup the next morning', true, 0, 0),
('lied to a partner about where I was', true, 0, 0),
('hooked up with someone on a first date', true, 0, 0),
('had a friends-with-benefits situation', true, 0, 0),
('been in a "situationship" I couldn''t explain to anyone', true, 0, 0),
('flirted with someone just to get something for free', true, 0, 0),
('had a wet dream about someone currently at this table', true, 0, 0),
('kissed someone whose name I didn''t actually know', true, 0, 0);
