-- Append batch 2 of curated Never Have I Ever statements.
insert into nhie_statements (statement, dirty, like_count, dislike_count) values
('sent a message meant for a group chat to the wrong person', false, 0, 0),
('pretended to understand a conversation I had no idea about', false, 0, 0),
('eaten something off someone''s plate without asking', false, 0, 0),
('fallen asleep during a movie at the theater', false, 0, 0),
('lied about my age to get a discount', false, 0, 0),
('forgotten someone''s name seconds after being introduced', false, 0, 0),
('worn mismatched shoes without realizing it', false, 0, 0),
('pretended to be sick to get out of something', false, 0, 0),
('gone to the wrong house thinking it was a friend''s', false, 0, 0),
('spilled a drink on someone at a party', false, 0, 0),
('forgotten I was on mute and said something I shouldn''t have', false, 0, 0),
('pretended not to see someone to avoid saying hi', false, 0, 0),
('lost a bet and had to do something embarrassing', false, 0, 0),
('accidentally liked something from years ago while scrolling', false, 0, 0),
('forgotten my own phone number when asked', false, 0, 0),
('taken a nap that lasted way longer than planned', false, 0, 0),
('had a crush on someone at this table right now', true, 0, 0),
('lied about my body count', true, 0, 0),
('hooked up with a friend''s ex', true, 0, 0),
('sent a flirty text to the wrong person', true, 0, 0),
('had a one-night stand I never told anyone about', true, 0, 0),
('gotten caught checking someone out', true, 0, 0),
('had a much older or younger crush than I''d admit', true, 0, 0),
('kissed two different people in the same night', true, 0, 0),
('pretended to be single when I wasn''t', true, 0, 0),
('had a crush on someone I met online and never in person', true, 0, 0),
('gotten feelings for someone I said "it''s just casual" about', true, 0, 0),
('flirted with someone to make another person jealous', true, 0, 0),
('had a secret relationship no one knew about', true, 0, 0),
('hooked up with someone I met that same night at a party', true, 0, 0),
('thought about an ex while with someone else', true, 0, 0);
