-- Replace all Category Countdown prompts with the curated 79-item set.
-- Counts reassigned by difficulty: harder categories -> 5 items to name, easier -> up to 10.

delete from category_prompts;

insert into category_prompts (text, count, dirty, like_count, dislike_count) values
('Name 10 countries in Europe.', 10, false, 0, 0),
('Name 10 pizza toppings.', 10, false, 0, 0),
('Name 10 breakfast foods.', 10, false, 0, 0),
('Name 7 classic sitcoms.', 7, false, 0, 0),
('Name 8 Marvel movies.', 8, false, 0, 0),
('Name 7 NBA teams.', 7, false, 0, 0),
('Name 10 ice cream flavors.', 10, false, 0, 0),
('Name 10 things you''d find in a bathroom.', 10, false, 0, 0),
('Name 5 boy bands or girl groups.', 5, false, 0, 0),
('Name 9 video games.', 9, false, 0, 0),
('Name 5 countries in Africa.', 5, false, 0, 0),
('Name 7 types of pasta.', 7, false, 0, 0),
('Name 6 James Bond movies.', 6, false, 0, 0),
('Name 6 famous talk show hosts.', 6, false, 0, 0),
('Name 8 rappers.', 8, false, 0, 0),
('Name 7 romantic comedy movies.', 7, false, 0, 0),
('Name 9 things you''d pack for a road trip.', 9, false, 0, 0),
('Name 9 US states.', 9, false, 0, 0),
('Name 5 fictional wizards or witches.', 5, false, 0, 0),
('Name 6 reality TV shows.', 6, false, 0, 0),
('Name 10 things that are red.', 10, false, 0, 0),
('Name 8 excuses for being late.', 8, false, 0, 0),
('Name 9 chocolate or candy bars.', 9, false, 0, 0),
('Name 9 things you''d find in a gym bag.', 9, false, 0, 0),
('Name 8 types of sandwiches.', 8, false, 0, 0),
('Name 7 Pixar movies.', 7, false, 0, 0),
('Name 5 things that are illegal almost everywhere.', 5, false, 0, 0),
('Name 9 animals you''d see at a zoo.', 9, false, 0, 0),
('Name 8 dog breeds.', 8, false, 0, 0),
('Name 5 famous painters.', 5, false, 0, 0),
('Name 9 things you do before bed.', 9, false, 0, 0),
('Name 10 apps on your phone.', 10, false, 0, 0),
('Name 8 sodas or soft drinks.', 8, false, 0, 0),
('Name 8 things you''d bring to a deserted island.', 8, false, 0, 0),
('Name 9 things found at a wedding.', 9, false, 0, 0),
('Name 7 things that ruin a first date.', 7, false, 0, 0),
('Name 5 famous stand-up comedians.', 5, false, 0, 0),
('Name 6 90s cartoons.', 6, false, 0, 0),
('Name 5 fictional detectives.', 5, false, 0, 0),
('Name 9 things you''d find at the beach.', 9, false, 0, 0),
('Name 6 TV shows set in New York.', 6, false, 0, 0),
('Name 6 iconic movie couples.', 6, false, 0, 0),
('Name 10 things that are yellow.', 10, false, 0, 0),
('Name 8 types of nuts.', 8, false, 0, 0),
('Name 5 famous magicians.', 5, false, 0, 0),
('Name 8 excuses to leave a boring party.', 8, false, 0, 0),
('Name 5 famous DJs.', 5, false, 0, 0),
('Name 8 things people collect as a hobby.', 8, false, 0, 0),
('Name 9 things you''d find in an office.', 9, false, 0, 0),
('Name 6 famous rivers.', 6, false, 0, 0),
('Name 10 things that are round.', 10, false, 0, 0),
('Name 8 famous soccer players.', 8, false, 0, 0),
('Name 6 kinds of tea.', 6, false, 0, 0),
('Name 9 breakfast cereals.', 9, false, 0, 0),
('Name 5 famous mountains.', 5, false, 0, 0),
('Name 9 things in a school classroom.', 9, false, 0, 0),
('Name 9 things you''d find in a hotel room.', 9, false, 0, 0),
('Name 8 excuses for missing work.', 8, false, 0, 0),
('Name 6 famous chefs.', 6, false, 0, 0),
('Name 9 things that fly.', 9, false, 0, 0),
('Name 6 things you shouldn''t microwave.', 6, false, 0, 0),
('Name 7 amusement park rides.', 7, false, 0, 0),
('Name 8 things you''d find in grandma''s house.', 8, false, 0, 0),
('Name 9 things that are sticky.', 9, false, 0, 0),
('Name 8 places you shouldn''t have sex.', 8, true, 0, 0),
('Name 8 red flags in a relationship.', 8, true, 0, 0),
('Name 8 things people lie about on dating apps.', 8, true, 0, 0),
('Name 8 signs someone is flirting with you.', 8, true, 0, 0),
('Name 6 excuses for a bad hookup.', 6, true, 0, 0),
('Name 5 slang words for kissing.', 5, true, 0, 0),
('Name 8 things people do drunk that they regret.', 8, true, 0, 0),
('Name 8 cheesy pickup lines.', 8, true, 0, 0),
('Name 8 things you should never text an ex.', 8, true, 0, 0),
('Name 8 things you might find in a stranger''s bedroom.', 8, true, 0, 0),
('Name 7 hangover cures.', 7, true, 0, 0),
('Name 8 excuses for being single.', 8, true, 0, 0),
('Name 6 things people do to make an ex jealous.', 6, true, 0, 0),
('Name 8 instant turn-offs.', 8, true, 0, 0),
('Name 8 things you shouldn''t do at an office party.', 8, true, 0, 0);
