-- Append batches 6 and 7 of curated Never Have I Ever statements.
insert into nhie_statements (statement, dirty, like_count, dislike_count) values
('lied to a cop to get out of a ticket', false, 0, 0),
('left a fake review out of spite', false, 0, 0),
('rage quit a video game', false, 0, 0),
('talked to my pet like it could understand everything', false, 0, 0),
('eaten a mystery leftover I couldn''t identify', false, 0, 0),
('fallen asleep at work or in class', false, 0, 0),
('pretended to work out harder than I actually did', false, 0, 0),
('lied about my fitness routine', false, 0, 0),
('forgotten I had plans and double-booked myself', false, 0, 0),
('shown up to the gym and immediately left', false, 0, 0),
('sent a text while half asleep that made no sense', false, 0, 0),
('accidentally liked a really old post while stalking', false, 0, 0),
('gotten scammed online', false, 0, 0),
('pretended to understand a menu in another language', false, 0, 0),
('talked my way out of a parking ticket', false, 0, 0),
('gotten way too competitive over a board game', false, 0, 0),
('said something awkward just to fill silence', false, 0, 0),
('laughed at a stranger''s expense and felt bad after', false, 0, 0),
('pretended to be someone''s biggest fan to fit in', false, 0, 0),
('gotten caught talking about someone right as they walked in', false, 0, 0),
('binged an entire show in one sitting and regretted it', false, 0, 0),
('sent a message to an ex that I immediately regretted', true, 0, 0),
('stalked someone''s new partner online', true, 0, 0),
('compared myself to someone''s ex', true, 0, 0),
('gotten nervous just from a crush texting first', true, 0, 0),
('had a "type" my friends warned me about', true, 0, 0),
('kept talking to someone even after being told to stop', true, 0, 0),
('gotten caught staring at someone across the room', true, 0, 0),
('had a friend warn me a crush was bad news and ignored it', true, 0, 0),
('had feelings I never admitted to a close friend', true, 0, 0),
('stayed talking to someone I knew wasn''t good for me', true, 0, 0),
('gotten way too invested in someone I barely knew', true, 0, 0),
('had an ex try to win me back and considered it', true, 0, 0),
('lied about how a relationship actually ended', true, 0, 0),
('kept a photo of an ex longer than I should have', true, 0, 0),
('still checked an ex''s social media regularly', true, 0, 0),
('had someone I was into choose my friend instead', true, 0, 0),
('had a threesome', true, 0, 0),
('had sex in a public place', true, 0, 0),
('had a one-night stand with a total stranger', true, 0, 0),
('sent a nude', true, 0, 0),
('had sex on the first date', true, 0, 0),
('had sex with someone whose name I never actually learned', true, 0, 0),
('used a sex toy', true, 0, 0),
('hooked up in a bathroom at a party or bar', true, 0, 0),
('had sex in a car', true, 0, 0),
('faked finishing', true, 0, 0),
('had a hookup while on vacation I never mentioned again', true, 0, 0),
('had sex with someone I met less than 24 hours before', true, 0, 0),
('hooked up with a coworker', true, 0, 0),
('had a hookup end so awkwardly I left without saying goodbye', true, 0, 0),
('tried role-play with a partner', true, 0, 0),
('had an open relationship or "hall pass" arrangement', true, 0, 0),
('done something in bed I''ve never told anyone about', true, 0, 0),
('had a dare go further than expected', true, 0, 0),
('snuck someone out of the house', true, 0, 0),
('had morning-after regret so bad I left before they woke up', true, 0, 0),
('hooked up with someone at a wedding', true, 0, 0),
('had a quickie somewhere I really shouldn''t have', true, 0, 0),
('had a hookup I''d never admit to at this table', true, 0, 0);
