import { NhieStatement } from '../types/nhieStatement';

let idCounter = 1;
const now = () => new Date().toISOString();
const nextId = () => idCounter++;

export const localNhieStatements: NhieStatement[] = [
  { id: nextId(), created_at: now(), statement: 'cheated on a test', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "pretended to know a song I'd never heard", dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'fallen off a chair in public', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'texted my ex "accidentally on purpose"', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "gone through someone's phone without asking", dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'told a lie that spiraled out of control', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'shown up to the wrong event', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'peed in a pool', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "snooped through someone's search history", dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'gotten stuck in an elevator', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'lied about liking a gift', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "accidentally liked an old photo while stalking someone's profile", dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'cheated at a board game', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'sent a voice message and immediately regretted it', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'pretended to be someone else on a phone call', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'broken something valuable and blamed someone else', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'stayed friends with an ex', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'lied about my location to get out of plans', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'pretended to be busy just to avoid someone', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'gotten a bad haircut and pretended to love it', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'driven somewhere and forgotten why', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'faked an accent', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "snuck into a place I wasn't supposed to be", dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'accidentally sent a text to the person it was about', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had a crush on a teacher or coach', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'almost sent a nude to the wrong person', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'regretted a hookup the next morning', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'lied to a partner about where I was', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'hooked up with someone on a first date', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had a friends-with-benefits situation', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'been in a "situationship" I couldn\'t explain to anyone', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'flirted with someone just to get something for free', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had a wet dream about someone currently at this table', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "kissed someone whose name I didn't actually know", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'sent a message meant for a group chat to the wrong person', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'pretended to understand a conversation I had no idea about', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "eaten something off someone else's plate without asking", dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'fallen asleep during a movie at the theater', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'lied about my age to get a discount', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'forgotten someone\'s name seconds after being introduced', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'worn mismatched shoes without realizing it', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'pretended to be sick to get out of something', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "gone to the wrong house thinking it was a friend's", dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'spilled a drink on someone at a party', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "forgotten I was on mute and said something I shouldn't have", dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'pretended not to see someone to avoid saying hi', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'lost a bet and had to do something embarrassing', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'forgotten my own phone number when asked', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'taken a nap that lasted way longer than planned', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had a crush on someone at this table right now', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'lied about my body count', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "hooked up with a friend's ex", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'sent a flirty text to the wrong person', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had a one-night stand I never told anyone about', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'gotten caught checking someone out', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "had a much older or younger crush than I'd admit", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'kissed two different people in the same night', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "pretended to be single when I wasn't", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had a crush on someone I met online and never in person', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'gotten feelings for someone I said "it\'s just casual" about', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'flirted with someone to make another person jealous', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had a secret relationship no one knew about', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'hooked up with someone I met that same night at a party', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'thought about an ex while with someone else', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'showed up an hour early to something by mistake', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'forgotten to hit send on a message and found it days later', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'gotten scared by my own reflection', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'accidentally worn my shirt inside out all day', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'gotten a haircut right before a big event and regretted it', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'laughed at my own joke before finishing it', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'pretended to be on the phone to avoid a stranger', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'sent an email to the wrong recipient at work', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "gotten a song's lyrics wrong for years without realizing it", dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "said \"love you\" to someone I wasn't supposed to, out of habit", dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'accidentally posted something meant to stay a draft', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had a crush that lasted way longer than it should have', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'hooked up with someone right after a breakup', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had feelings for two people at the same time', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'stayed up all night texting someone new', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had a workplace crush I never acted on', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'gone on a date I regretted within five minutes', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had a friendship almost turn into something more', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "lied about how many people I've dated", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had someone find out I liked them before I told them', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'felt jealous seeing an ex with someone new', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had a crush confess to me and panicked', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'flirted back and forth for weeks without making a move', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'thought "this could be the one" way too early', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'cheated on a partner and never got caught', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'been cheated on and stayed anyway', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'wanted a threesome', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'slept with someone just to make an ex jealous', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'kept someone as a "backup option" while dating someone else', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "read a partner's private messages without permission", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'ghosted someone right after sleeping with them', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'hooked up with someone way older or younger than me', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "had an unrequited crush on a close friend's partner", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "kept messaging an ex behind my partner's back", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'fantasized about someone else while with my partner', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'said "I love you" and didn\'t fully mean it', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had a pregnancy scare', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "been the \"other person\" in someone else's relationship", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "deleted messages so a partner wouldn't see them", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'used someone for their money or status', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "gotten drunk and revealed a secret I really shouldn't have", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'lied to my family about who I was dating', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'kept an entire relationship secret from my parents', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'hooked up with someone I met on a work or school trip', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'stayed friends with someone specifically hoping for more', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'lied about being exclusive with someone', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "had someone else's name almost slip out at the wrong moment", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'hooked up with two people who know each other', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'been in love with someone who was already taken', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'told a friend\'s secret to someone else', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'dated someone just to get back at an ex', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'lied about my income to impress someone', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'borrowed money and never paid it back', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'talked badly about a friend to someone they were dating', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'hooked up with someone my friend had feelings for', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'pretended not to remember a hookup out of pure embarrassment', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'sabotaged someone else\'s relationship on purpose', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'lied to a partner about my past', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'used a fake name on a date', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'stayed in a relationship only because I was scared to be alone', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'told someone I loved them just to keep them around', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'cried to get out of trouble', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'lied about where money went in a relationship', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "snooped through a partner's phone and found something I regret seeing", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'found out I was someone\'s "backup" and stayed anyway', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "lied about liking someone's family just to keep the peace", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "pretended to have moved on from an ex when I really hadn't", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'compared a current partner to an ex out loud', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "hooked up with someone and pretended I didn't remember their name", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'broken up with someone over text', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "been jealous of a friend's relationship", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "wished something bad on an ex's new partner", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "stayed friends with someone I secretly couldn't stand", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'lied to a cop to get out of a ticket', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'left a fake review out of spite', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'rage quit a video game', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'talked to my pet like it could understand everything', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "eaten a mystery leftover I couldn't identify", dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'fallen asleep at work or in class', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'pretended to work out harder than I actually did', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'lied about my fitness routine', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'forgotten I had plans and double-booked myself', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'shown up to the gym and immediately left', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'sent a text while half asleep that made no sense', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'gotten scammed online', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'pretended to understand a menu in another language', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'talked my way out of a parking ticket', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'gotten way too competitive over a board game', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'said something awkward just to fill silence', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "laughed at a stranger's expense and felt bad after", dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "pretended to be someone's biggest fan to fit in", dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'gotten caught talking about someone right as they walked in', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'binged an entire show in one sitting and regretted it', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'sent a message to an ex that I immediately regretted', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "stalked someone's new partner online", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "compared myself to someone's ex", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'gotten nervous just from a crush texting first', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had a "type" my friends warned me about', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'kept talking to someone even after being told to stop', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had a friend warn me a crush was bad news and ignored it', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had feelings I never admitted to a close friend', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "stayed talking to someone I knew wasn't good for me", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'gotten way too invested in someone I barely knew', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had an ex try to win me back and considered it', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'lied about how a relationship actually ended', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'kept a photo of an ex longer than I should have', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "still checked an ex's social media regularly", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had someone I was into choose my friend instead', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had a threesome', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had sex in a public place', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had a one-night stand with a total stranger', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'sent a nude', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had sex on the first date', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had sex with someone whose name I never actually learned', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'used a sex toy', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'hooked up in a bathroom at a party or bar', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had sex in a car', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'faked finishing', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had a hookup while on vacation I never mentioned again', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had sex with someone I met less than 24 hours before', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'hooked up with a coworker', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had a hookup end so awkwardly I left without saying goodbye', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'tried role-play with a partner', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had an open relationship or "hall pass" arrangement', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "done something in bed I've never told anyone about", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had a dare go further than expected', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'snuck someone out of the house', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had morning-after regret so bad I left before they woke up', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'hooked up with someone at a wedding', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "had a quickie somewhere I really shouldn't have", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "had a hookup I'd never admit to at this table", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'lied about my "number" to seem less experienced', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "pretended an ex didn't exist when talking to someone new", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "had a friend's ex hit on me", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'gotten caught by a roommate mid-hookup', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had a hookup buddy for over a year', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "slid back into an ex's DMs after months of no contact", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had a one-night stand turn into something longer', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'lied about liking something in bed to avoid an awkward talk', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'hooked up with someone purely out of boredom', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'used alcohol as an excuse for a hookup I actually wanted', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'said "we\'re just having fun" when it clearly wasn\'t just fun for me', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'texted an ex while in a new relationship', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "had an ex's friend message me", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'pretended to be more experienced than I actually am', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "had someone find messages on my phone I didn't want them to see", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'sent something risky to the wrong group chat', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had a hookup I only remember parts of', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "had to ask for someone's name again the next morning", dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'been accused of cheating when I actually was', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'lied about being ready for a relationship just to keep someone around', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'lied on my resume or CV', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'googled my symptoms and convinced myself I was dying', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "pretended to be happy for someone when I really wasn't", dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "avoided answering a call because I didn't want to deal with it", dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "lied to a friend about why I couldn't make it to something", dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'pretended not to care about something that really hurt', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'lied to get out of paying for something', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "taken credit for someone else's idea", dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'avoided a friend for weeks without telling them why', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "pretended to laugh at a joke I didn't actually understand", dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'said something petty just to win an argument', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'lied about being busy to skip a family event', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "judged someone based on their appearance and regretted it", dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'talked myself out of an opportunity out of fear', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'pretended not to notice someone was upset with me', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "gone into debt for something I didn't need", dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'hidden a purchase from a partner or family member', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'lied about how much something cost', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'let someone take the blame for something I did', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'avoided a family member on purpose for months', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'lied about how I really feel just to keep the peace', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'lied about myself on a dating app', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'taken a solo trip', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: "changed someone's mind about something important", dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'sent an anonymous gift', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'spied on my neighbors', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'stolen something small from a restaurant', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'made up a story about myself to impress someone', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had a wardrobe malfunction in public', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'snuck into a movie or concert without paying', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'lied about my job to sound cooler', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'sent a text to the wrong person on purpose', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'kissed a stranger', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'ghosted someone I was dating', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'fallen in love at first sight', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'flirted with a bartender or barista', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'climbed a mountain', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'ridden a camel', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'been in a cave', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'been to a major festival like Coachella', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'lost a personal item in another country', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'been to a major sports final', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'laughed so hard I spit out my drink', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'tried to impress someone and failed miserably', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had a funny misunderstanding', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'tried to sound smart and made a fool of myself', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'accidentally waved at a stranger thinking I knew them', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'learned a language to better communicate with someone', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'dined and dashed', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'lied to someone playing this game right now', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'drunk texted an ex', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'started a rumor', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'convinced a friend to dump their partner', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'fought with someone in public', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'gotten into a car crash', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'tried psychedelics', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had a video go viral', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'regifted something', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'met a celebrity', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'done a prank call', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'participated in a protest', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'peed my pants as an adult', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'been to a strip club', dirty: true, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'been on a blind date', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'had a paranormal experience', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'been to a fortune teller', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'been hypnotized', dirty: false, like_count: 0, dislike_count: 0 },
  { id: nextId(), created_at: now(), statement: 'collected stamps, coins, or trading cards', dirty: false, like_count: 0, dislike_count: 0 },
];

export function nextNhieId(): number {
  const ids = localNhieStatements.map((s) => s.id);
  return (ids.length ? Math.max(...ids) : 0) + 1;
}

export function nhieNowIso(): string {
  return now();
}
